"""init2

Revision ID: 46e486c2cdd0
Revises: 8adbfee4900e
Create Date: 2022-06-27 09:46:47.673647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46e486c2cdd0'
down_revision = '8adbfee4900e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameshistory',
    sa.Column('game_id', postgresql.UUID(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('field_size', sa.Integer(), nullable=False),
    sa.Column('victory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_gameshistory_telegram_id'), 'gameshistory', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gameshistory_telegram_id'), table_name='gameshistory')
    op.drop_table('gameshistory')
    # ### end Alembic commands ###
